### ISSUE TITLE
Error when using viewTargetAlignment

### ISSUE THREAD

**Issue by Zehuan-D** [ETHZ-INS/scanMiR#19]
Hello,

Thank you for developing such a useful tool!
However, when I use viewTargetAlignment, it always gives the error below:
> viewTargetAlignment(matches[1], miRNA, seqs = transcript)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'subseq': input must be a single non-NA string

When I test with the "SampleTranscript", there is no such error.

Here is what I did to find the match:
> matches <- findSeedMatches(transcript, miRNA, verbose = FALSE, keepMatchSeq = TRUE)
> matches
GRanges object with 1 range and 4 metadata columns:
      seqnames    ranges strand |     type sequence  p3.score  note
         <Rle> <IRanges>  <Rle> | <factor> <factor> <integer> <Rle>
  [1]     seq1   361-368      * |  7mer-m8 TGCTGCTT         2     -
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths

Could you please help with that?

Thank you for your time!

**Comment by michasou** [comment]
Hi  there, please excuse the late reply, it seems we sometimes don't receive notifications regarding new issues. 
Regarding your error, could it be that the `transcript` you provide in `seqs` in the `viewTargetAlignment` function has another name as the entry in `m`? 

To easily circumvent this issue, can you try to set `p3.extra=TRUE` in the `findSeedmatches` function?

Hope this helps and let us know in case not! If you provide more specific information regarding the sequence and miRNA we can also try to reproduce the error here.

Best, Michael

**Comment by Zehuan-D** [comment]
Hello Michael,

Thank you for the information!
I realized that I did assign the `transcript` with another name and used `seqs = name` . It works now, thank you for your help!

Best,
Zehuan
