### ISSUE TITLE
Call pwalign::nucleotideSubstitutionMatrix() in findSeedMatches to avoid warning

### ISSUE THREAD

**Issue by michasou** [ETHZ-INS/scanMiR#20]
nucleotideSubstitutionMatrix() has moved to the pwalign package. Please call pwalign::nucleotideSubstitutionMatrix() to get rid of this warning.

>> Correct in FindSeedMatches and import new package...

**Comment by plger** [comment]
thanks, this was fixed in bioconductor devel, now pull the change to this github repo.
